### ISSUE TITLE
Not working in child process to parent process

### ISSUE THREAD

**Issue by mqliutie** [Gozala/events#72]
parent.js 
```
spawn('npm',['run','server'])
event.on('server-start-success', function(){
  console.log('server start success')
})
```

child.js
```
event.emit('server-start-success');
```

**Comment by goto-bus-stop** [comment]
That's right, you can't use `events` that way. To emit an event you need to use the same EventEmitter object that has the event handlers, but JS objects cannot be shared between processes, so that is impossible. You need to use some form of IPC, with [https://nodejs.org/api/child_process.html#child_process_child_process_fork_modulepath_args_options](child_process.fork()] for example.
