### ISSUE TITLE
spliceOne performance

### ISSUE THREAD

**Issue by betula** [Gozala/events#73]
Why you don't use standard JS "Array.prototype.splice" for it?
(Performance reasons https://jsperf.com/splice-vs-events-spliceone)
```JS
function spliceOne(list, index) {
  for (; index + 1 < list.length; index++)
    list[index] = list[index + 1];
  list.pop();
}
```
https://github.com/Gozala/events/blob/master/events.js#L434-L438

**Comment by goto-bus-stop** [comment]
The reason _we_ use it is because node.js does, and `events` tries to stay as close as possible to the node.js source code so applying changes from future node.js updates is easier.

node.js uses it because they've benchmarked it and found it faster, although of course that can change over time with V8 updates!

Right now, spliceOne is faster for me in both cases on Firefox:
![image](https://user-images.githubusercontent.com/1006268/72718006-65999d80-3b75-11ea-98d0-0860c799bb7e.png)
And on Chrome the difference is negligible:
![image](https://user-images.githubusercontent.com/1006268/72718227-d2ad3300-3b75-11ea-85df-3ee5bfb26d2c.png)

I think typically with event emitters, the most common case is removing a listener from the tail, and removing listeners from somewhere in the middle. Unfortunately I can't manage to log in to jsperf to add that last case :(
